FROM tensorflow/tensorflow:2.14.0rc0

WORKDIR /app
#COPY ./flask/requirements.txt /app
#RUN pip install -r requirements.txt

#COPY ./requirements.txt /app
COPY . .

#ignore tensorflow dependency in requirements.txt
#RUN pip install --root-user-action=ignore $(grep -ivE "tensorflow" requirements.txt) --ignore-installed
RUN pip install --root-user-action=ignore -r requirements.txt --ignore-installed
RUN playwright install
RUN playwright install-deps

EXPOSE 5000
WORKDIR /app/flask
ENV FLASK_APP=main.py
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5000"]
#CMD ["flask", "run", "--host", "0.0.0.0","--port","5000"]